### ISSUE TITLE
Error when requirements.txt tries to install py-cord[voice]

### ISSUE THREAD

**Issue by Afjis** [Krutyi-4el/DandelionMusic#37]
Hello, I'm having a problem when it comes to installing the requirements. When it gets to the py-cord[voice] installation it throws this error

```
Defaulting to user installation because normal site-packages is not writeable
Collecting py-cord[voice]
  Using cached https://github.com/Krutyi-4el/pycord/archive/9c5af3d15e3011ff1e29b55e3b1063391d0455d6.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Generating metadata for package py-cord produced metadata for project name unknown. Fix your #egg=py-cord fragments.
Discarding https://github.com/Krutyi-4el/pycord/archive/9c5af3d15e3011ff1e29b55e3b1063391d0455d6.zip#egg=py-cord: Requested unknown from https://github.com/Krutyi-4el/pycord/archive/9c5af3d15e3011ff1e29b55e3b1063391d0455d6.zip#egg=py-cord (from -r requirements.txt (line 1)) has inconsistent name: filename has 'py-cord', but metadata has 'unknown'
ERROR: Could not find a version that satisfies the requirement py-cord (unavailable) (from versions: 1.7.3, 2.0.0b1, 2.0.0b2, 2.0.0b3, 2.0.0b4, 2.0.0b5, 2.0.0b6, 2.0.0b7, 2.0.0rc1, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.4.0, 2.4.1)
ERROR: No matching distribution found for py-cord (unavailable)
```

I'm not quite sure how to go about fixing this, so any help would be greatly appreciated.

**Comment by Krutyi-4el** [comment]
1. Please make sure that you're running the newest version of the bot 
2. Send your pip version here (output of `pip --version`)

**Comment by Afjis** [comment]
I should be running the latest version of the bot, however I am hosting on a Linux Ubuntu server so I just git clone the repository. I'm not sure if that clones the latest release or not.
The output for my pip version is `pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)`

**Comment by Krutyi-4el** [comment]
Yes, it does clone the last version. However, you should run `git pull origin master` if the repo was updated after you've cloned it.

You can try installing the dependencies in a virtual environment (`python3 -m venv bot_env && . bot_env/bin/activate`). If that fails, share the output of `pip -v install -r requirements.txt`.

**Comment by Afjis** [comment]
Installing in a virtual environment worked. The bot seems to be working perfectly. The only thing that I had to do after the venv, was pip install aiosqlite. Although while as of now it isn't affecting anything I am getting an error:
```
[tls @ 0x5619eba36e00] Error in the pull function.
[https @ 0x5619eba336c0] Will reconnect at 3588080 in 0 second(s), error=Input/output error.
```
It seems this error pops after after playing a song for a while, it doesn't stop the song or affect the bot, and it has only happened twice so far so I'm unsure if it's a real problem or not. But the bot is indeed working now, so thank you

**Comment by Krutyi-4el** [comment]
Glad to hear it works now.

> The only thing that I had to do after the venv, was pip install aiosqlite

Interesting, because it should've been installed automatically as dependency of `./config`. If you by any chance gather some info about why it wasn't installed automatically, please open an issue describing it.

> I'm unsure if it's a real problem or not

I don't think it is. It indicates that YouTube terminates the connection, but we're reconnecting immediately.

**Comment by SenninMoodo** [comment]
Hey,
came across the same problem as @Afjis and installing it into a venv solved it for me as well.

But I'm getting the same errors when it comes to YT connections at least twice per song and I'm curious if this really won't cause any problems cause besides having the output spammed, the last time I tried playing a playlist from yt it just stopped after the first song.
Example output:
`[tls @ 0x564b12c50240] Error in the pull function.
[https @ 0x564b12b92740] Will reconnect at 1736704 in 0 second(s), error=Input/output error.
[tls @ 0x564b12f09e40] Error in the pull function.
[https @ 0x564b12b92740] Will reconnect at 2359280 in 0 second(s), error=Input/output error.
`

Note: yt-dlp throws a warning as well which can be fixed by simply updating it as the warning indicates.

**Comment by Krutyi-4el** [comment]
@SenninMoodo try the newest version. If it unexpectedly stops playing, open an issue about that.
